### PR TITLE
feat: only-allow pnpm

### PR DESCRIPTION
**Pull request by code-ManL**

### CODE REVIEW

**Review by sxzz — APPROVED** [review]

**Comment by code-ManL** [comment]
i rebase the latest commit.

**Comment by sodatea** [comment]
Actually, `only-allow` doesn't work on npm 7+ https://github.com/npm/cli/issues/2660

**Comment by code-ManL** [comment]
The node version needs to be greater than 18 when installing dependencies, so I think the npm version will not be very low at this time

**Comment by luojinan** [comment]
But preinstall hook is also can't stop the installation proceed  in node 18.15.0 & npm 9.5 [https://github.com/npm/cli/issues/2660](https://github.com/npm/cli/issues/2660)

**Pull request merged**
